name: Keepalive Workflow

on:
  schedule:
    - cron: "0 0 1 * *" # 毎月1日 UTC 0:00
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v2
